### ISSUE TITLE
How can I remove the Appointment Form default fields?

### ISSUE THREAD

**Issue by sofiansamamr** [DevExpress/devextreme-documentation#4225]
![image](https://user-images.githubusercontent.com/82759808/192794025-cc4ff570-f08e-4907-9211-b5967feade2b.png)

Is there a way to permanently remove these fields?

Thanks in advance.

**Comment by AlisherAmonulloev** [comment]
@sofiansamamr,

The Scheduler component uses the Form control in its Appointment Form dialog. The component fires the `onAppointmentFormOpening` callback when the dialog is about to be opened. You can use the Form control's API to hide or remove these fields. Please refer to the following help topic to see what parameters the callback has: [https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#onAppointmentFormOpening](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#onAppointmentFormOpening).

To see the Form control's API, check the following help topic: [https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxForm/Methods/#itemOptionid_option_value](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxForm/Methods/#itemOptionid_option_value).

If you have further questions, feel free to create a support ticket in our Support Center: [https://www.devexpress.com/ask](https://www.devexpress.com/ask).
