### ISSUE TITLE
how to run as static site

### ISSUE THREAD

**Issue by OxPatient** [DevExpress/devextreme-documentation#63]
how to run as static site

**Comment by RomanTsukanov** [comment]
Hi OxPatient,

Currently, we do not provide this capability. You can navigate through the documentation right here, on GitHub - the links in the documents are valid.

Could you please clarify why you need to run the site locally?

**Comment by RomanTsukanov** [comment]
The issue has been closed due to inactivity.
Please file a new issue if you are encountering a similar or related problem.
